api = "0.8"

[buildpack]
  description = "A buildpack for installing the appropriate .NET Core SDK version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-sdk"
  id = "paketo-buildpacks/dotnet-core-sdk"
  keywords = ["dotnet", "runtime"]
  name = "Paketo Buildpack for .NET Core SDK"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-sdk/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.configurations]]
    build = true
    description = "specify a version of SDK to use"
    name = "BP_DOTNET_SDK_VERSION"
  [metadata.default-versions]
    dotnet-sdk = "8.*"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:934b8060a7190e5909ad1fd0785db542f487b3bbf6cdd14826b02095fdd0d0394298b1634085eff302928fccc33f7c1a7253e9b87df555fc36fce819bcd2e798"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.425:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@8.0.425?checksum=934b8060a7190e5909ad1fd0785db542f487b3bbf6cdd14826b02095fdd0d0394298b1634085eff302928fccc33f7c1a7253e9b87df555fc36fce819bcd2e798&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.425/dotnet-sdk-8.0.425-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.425/dotnet-sdk-8.0.425-linux-x64.tar.gz"
    source-checksum = "sha512:934b8060a7190e5909ad1fd0785db542f487b3bbf6cdd14826b02095fdd0d0394298b1634085eff302928fccc33f7c1a7253e9b87df555fc36fce819bcd2e798"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.425/dotnet-sdk-8.0.425-linux-x64.tar.gz"
    version = "8.0.425"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:84a4d017d74d7aa842e981679d1b044e6be1f35b9b2b214021e30bc40871d016d29611cca373d8502ad5c890e3ad360ee698f9cf2d7a4d5a9fba102d88ba310f"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.425:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@8.0.425?checksum=84a4d017d74d7aa842e981679d1b044e6be1f35b9b2b214021e30bc40871d016d29611cca373d8502ad5c890e3ad360ee698f9cf2d7a4d5a9fba102d88ba310f&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.425/dotnet-sdk-8.0.425-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.425/dotnet-sdk-8.0.425-linux-arm64.tar.gz"
    source-checksum = "sha512:84a4d017d74d7aa842e981679d1b044e6be1f35b9b2b214021e30bc40871d016d29611cca373d8502ad5c890e3ad360ee698f9cf2d7a4d5a9fba102d88ba310f"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.425/dotnet-sdk-8.0.425-linux-arm64.tar.gz"
    version = "8.0.425"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:e8685293a3512178e0de1bb3c1663e31fdf9d761af705094bf833cc1ff6b9a18c543aa4141f0216503c98039c719585a6d32905b0bbb3279e93b7e7616e047c3"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.318:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@9.0.318?checksum=e8685293a3512178e0de1bb3c1663e31fdf9d761af705094bf833cc1ff6b9a18c543aa4141f0216503c98039c719585a6d32905b0bbb3279e93b7e7616e047c3&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.318/dotnet-sdk-9.0.318-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.318/dotnet-sdk-9.0.318-linux-x64.tar.gz"
    source-checksum = "sha512:e8685293a3512178e0de1bb3c1663e31fdf9d761af705094bf833cc1ff6b9a18c543aa4141f0216503c98039c719585a6d32905b0bbb3279e93b7e7616e047c3"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.318/dotnet-sdk-9.0.318-linux-x64.tar.gz"
    version = "9.0.318"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:f9c957867bddea8f82ec0459432ce7ddff8fafc846537b8003eb9f239d9c2e38586031a15954e74691c5a8cf5b3ab125d99bca85c74ca45dc8745071ca81e7ff"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.318:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@9.0.318?checksum=f9c957867bddea8f82ec0459432ce7ddff8fafc846537b8003eb9f239d9c2e38586031a15954e74691c5a8cf5b3ab125d99bca85c74ca45dc8745071ca81e7ff&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.318/dotnet-sdk-9.0.318-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.318/dotnet-sdk-9.0.318-linux-arm64.tar.gz"
    source-checksum = "sha512:f9c957867bddea8f82ec0459432ce7ddff8fafc846537b8003eb9f239d9c2e38586031a15954e74691c5a8cf5b3ab125d99bca85c74ca45dc8745071ca81e7ff"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.318/dotnet-sdk-9.0.318-linux-arm64.tar.gz"
    version = "9.0.318"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:51c8b999af9e8dd9998c9edc5944e19a90788862068acd38694e098889054ce8c23d4f0c5cccfa16bf187d044562359e5ee69a9f8ad0bbe913ba90311fbce25b"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.401:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@10.0.401?checksum=51c8b999af9e8dd9998c9edc5944e19a90788862068acd38694e098889054ce8c23d4f0c5cccfa16bf187d044562359e5ee69a9f8ad0bbe913ba90311fbce25b&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.401/dotnet-sdk-10.0.401-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.401/dotnet-sdk-10.0.401-linux-x64.tar.gz"
    source-checksum = "sha512:51c8b999af9e8dd9998c9edc5944e19a90788862068acd38694e098889054ce8c23d4f0c5cccfa16bf187d044562359e5ee69a9f8ad0bbe913ba90311fbce25b"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.401/dotnet-sdk-10.0.401-linux-x64.tar.gz"
    version = "10.0.401"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:58ace73ced6b4360754689a686bdfb8a317f4da6cb8bb416dbc7d0ba9f47e43e3c09f5eb1f1a1cfaacbd10df9558da4882bf2a5e195d6ab56a02c1f9f76102ed"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.401:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@10.0.401?checksum=58ace73ced6b4360754689a686bdfb8a317f4da6cb8bb416dbc7d0ba9f47e43e3c09f5eb1f1a1cfaacbd10df9558da4882bf2a5e195d6ab56a02c1f9f76102ed&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.401/dotnet-sdk-10.0.401-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.401/dotnet-sdk-10.0.401-linux-arm64.tar.gz"
    source-checksum = "sha512:58ace73ced6b4360754689a686bdfb8a317f4da6cb8bb416dbc7d0ba9f47e43e3c09f5eb1f1a1cfaacbd10df9558da4882bf2a5e195d6ab56a02c1f9f76102ed"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.401/dotnet-sdk-10.0.401-linux-arm64.tar.gz"
    version = "10.0.401"

  [[metadata.dependency-constraints]]
    constraint = "8.0.*"
    id = "dotnet-sdk"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "9.0.*"
    id = "dotnet-sdk"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "10.0.*"
    id = "dotnet-sdk"
    patches = 1

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
