api = "0.8"

[buildpack]
  description = "A buildpack for installing the appropriate .NET Core SDK version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-sdk"
  id = "paketo-buildpacks/dotnet-core-sdk"
  keywords = ["dotnet", "runtime"]
  name = "Paketo Buildpack for .NET Core SDK"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-sdk/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.configurations]]
    build = true
    description = "specify a version of SDK to use"
    name = "BP_DOTNET_SDK_VERSION"
  [metadata.default-versions]
    dotnet-sdk = "8.*"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:6503fd9f464d5e3a4f43a881d2b74afc6a2c46ceda74d027f1565b7239f4b3ec884857c03c0dcd49eb52f384d5ae1fa5aaf135f0a6aabc5518103aceed643c74"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.424:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@8.0.424?checksum=6503fd9f464d5e3a4f43a881d2b74afc6a2c46ceda74d027f1565b7239f4b3ec884857c03c0dcd49eb52f384d5ae1fa5aaf135f0a6aabc5518103aceed643c74&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.424/dotnet-sdk-8.0.424-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.424/dotnet-sdk-8.0.424-linux-x64.tar.gz"
    source-checksum = "sha512:6503fd9f464d5e3a4f43a881d2b74afc6a2c46ceda74d027f1565b7239f4b3ec884857c03c0dcd49eb52f384d5ae1fa5aaf135f0a6aabc5518103aceed643c74"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.424/dotnet-sdk-8.0.424-linux-x64.tar.gz"
    version = "8.0.424"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:bb19b6779ad93d146055583d644ef269bb42501f6c7fdef51e14026cde9d5fd726d370de098a8d8504867fb24bfcb5ab88cc22bec812461aede334de1aacf7b6"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.424:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@8.0.424?checksum=bb19b6779ad93d146055583d644ef269bb42501f6c7fdef51e14026cde9d5fd726d370de098a8d8504867fb24bfcb5ab88cc22bec812461aede334de1aacf7b6&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.424/dotnet-sdk-8.0.424-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.424/dotnet-sdk-8.0.424-linux-arm64.tar.gz"
    source-checksum = "sha512:bb19b6779ad93d146055583d644ef269bb42501f6c7fdef51e14026cde9d5fd726d370de098a8d8504867fb24bfcb5ab88cc22bec812461aede334de1aacf7b6"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.424/dotnet-sdk-8.0.424-linux-arm64.tar.gz"
    version = "8.0.424"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:145bf69dcb88c4b905feb531cfdd7894a75fc875d2a030e958a13d1fb1131521c8cebd8a8a6e0fbd1a433ebae9cde86356b6adad07b1ad81efb92b36ff8a3333"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.317:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@9.0.317?checksum=145bf69dcb88c4b905feb531cfdd7894a75fc875d2a030e958a13d1fb1131521c8cebd8a8a6e0fbd1a433ebae9cde86356b6adad07b1ad81efb92b36ff8a3333&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.317/dotnet-sdk-9.0.317-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.317/dotnet-sdk-9.0.317-linux-x64.tar.gz"
    source-checksum = "sha512:145bf69dcb88c4b905feb531cfdd7894a75fc875d2a030e958a13d1fb1131521c8cebd8a8a6e0fbd1a433ebae9cde86356b6adad07b1ad81efb92b36ff8a3333"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.317/dotnet-sdk-9.0.317-linux-x64.tar.gz"
    version = "9.0.317"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:fdf30fe705c91304d890115e955f738055f8c0885ea9891e7df1153321120fa2c38b6ae4dd132f871cb8facc0d1fabbd2b25ddd53d0a5b4293aa85d296e3b98d"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.317:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@9.0.317?checksum=fdf30fe705c91304d890115e955f738055f8c0885ea9891e7df1153321120fa2c38b6ae4dd132f871cb8facc0d1fabbd2b25ddd53d0a5b4293aa85d296e3b98d&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.317/dotnet-sdk-9.0.317-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.317/dotnet-sdk-9.0.317-linux-arm64.tar.gz"
    source-checksum = "sha512:fdf30fe705c91304d890115e955f738055f8c0885ea9891e7df1153321120fa2c38b6ae4dd132f871cb8facc0d1fabbd2b25ddd53d0a5b4293aa85d296e3b98d"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.317/dotnet-sdk-9.0.317-linux-arm64.tar.gz"
    version = "9.0.317"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:1033977dd837150e0814cf0c5d5b17ceb63925fda7ba2158b47258a4bd7c048cf82eac3bc1166f3146f53124a3f5fba09db1de1260d2ce96399860303b404b48"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.400:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@10.0.400?checksum=1033977dd837150e0814cf0c5d5b17ceb63925fda7ba2158b47258a4bd7c048cf82eac3bc1166f3146f53124a3f5fba09db1de1260d2ce96399860303b404b48&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.400/dotnet-sdk-10.0.400-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.400/dotnet-sdk-10.0.400-linux-x64.tar.gz"
    source-checksum = "sha512:1033977dd837150e0814cf0c5d5b17ceb63925fda7ba2158b47258a4bd7c048cf82eac3bc1166f3146f53124a3f5fba09db1de1260d2ce96399860303b404b48"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.400/dotnet-sdk-10.0.400-linux-x64.tar.gz"
    version = "10.0.400"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:a1b45da58e5591fff909a6126ac6bfc1ef9c12bc72c0625f7815e83a82be1a902317ee96926cbbf81324a45c6abf2ed8102a216d0507879cc166159af78d1b77"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.400:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@10.0.400?checksum=a1b45da58e5591fff909a6126ac6bfc1ef9c12bc72c0625f7815e83a82be1a902317ee96926cbbf81324a45c6abf2ed8102a216d0507879cc166159af78d1b77&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.400/dotnet-sdk-10.0.400-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.400/dotnet-sdk-10.0.400-linux-arm64.tar.gz"
    source-checksum = "sha512:a1b45da58e5591fff909a6126ac6bfc1ef9c12bc72c0625f7815e83a82be1a902317ee96926cbbf81324a45c6abf2ed8102a216d0507879cc166159af78d1b77"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.400/dotnet-sdk-10.0.400-linux-arm64.tar.gz"
    version = "10.0.400"

  [[metadata.dependency-constraints]]
    constraint = "8.0.*"
    id = "dotnet-sdk"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "9.0.*"
    id = "dotnet-sdk"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "10.0.*"
    id = "dotnet-sdk"
    patches = 1

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
