api = "0.8"

[buildpack]
  description = "A buildpack for installing the appropriate .NET Core SDK version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-sdk"
  id = "paketo-buildpacks/dotnet-core-sdk"
  keywords = ["dotnet", "runtime"]
  name = "Paketo Buildpack for .NET Core SDK"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-sdk/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.configurations]]
    build = true
    description = "specify a version of SDK to use"
    name = "BP_DOTNET_SDK_VERSION"
  [metadata.default-versions]
    dotnet-sdk = "8.*"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:36c68c1be9d5c6f24cd8e6bd4b6d36bfd7ab724ac7e3499fb13e42e70a9003310e5ee5759ed19ced1f0ecd3d26a55f135c7e72d6f788e7d44f5f0eaa72ad9a07"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.420:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@8.0.420?checksum=36c68c1be9d5c6f24cd8e6bd4b6d36bfd7ab724ac7e3499fb13e42e70a9003310e5ee5759ed19ced1f0ecd3d26a55f135c7e72d6f788e7d44f5f0eaa72ad9a07&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.420/dotnet-sdk-8.0.420-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.420/dotnet-sdk-8.0.420-linux-x64.tar.gz"
    source-checksum = "sha512:36c68c1be9d5c6f24cd8e6bd4b6d36bfd7ab724ac7e3499fb13e42e70a9003310e5ee5759ed19ced1f0ecd3d26a55f135c7e72d6f788e7d44f5f0eaa72ad9a07"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.420/dotnet-sdk-8.0.420-linux-x64.tar.gz"
    version = "8.0.420"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:535197b224b52d77ce04f73656007886576662f12a8f3aff9ab87b16bb7e025edb2f94291bfb901772d76b7f686f974680743fef216daf491ef3617d9af12e8e"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.420:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@8.0.420?checksum=535197b224b52d77ce04f73656007886576662f12a8f3aff9ab87b16bb7e025edb2f94291bfb901772d76b7f686f974680743fef216daf491ef3617d9af12e8e&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.420/dotnet-sdk-8.0.420-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.420/dotnet-sdk-8.0.420-linux-arm64.tar.gz"
    source-checksum = "sha512:535197b224b52d77ce04f73656007886576662f12a8f3aff9ab87b16bb7e025edb2f94291bfb901772d76b7f686f974680743fef216daf491ef3617d9af12e8e"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.420/dotnet-sdk-8.0.420-linux-arm64.tar.gz"
    version = "8.0.420"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:cb2f09cc3e44be152e8f7abdfeb18040f6de5d8195bc723f584483775af169bfa5f17c03ce0cb64fa53bcc7d29eb7810684a3fa4cf6b228fa52ad132bf89bf62"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.313:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@9.0.313?checksum=cb2f09cc3e44be152e8f7abdfeb18040f6de5d8195bc723f584483775af169bfa5f17c03ce0cb64fa53bcc7d29eb7810684a3fa4cf6b228fa52ad132bf89bf62&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.313/dotnet-sdk-9.0.313-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.313/dotnet-sdk-9.0.313-linux-x64.tar.gz"
    source-checksum = "sha512:cb2f09cc3e44be152e8f7abdfeb18040f6de5d8195bc723f584483775af169bfa5f17c03ce0cb64fa53bcc7d29eb7810684a3fa4cf6b228fa52ad132bf89bf62"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.313/dotnet-sdk-9.0.313-linux-x64.tar.gz"
    version = "9.0.313"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:0278c86bcc9c9da2a2be0f43dd34a8cde2d4b1f541ad101c30db44d44536388fa641c57a07a7ac829b7d403112760b172dc608880f3214208827bb3205c01a60"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.313:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@9.0.313?checksum=0278c86bcc9c9da2a2be0f43dd34a8cde2d4b1f541ad101c30db44d44536388fa641c57a07a7ac829b7d403112760b172dc608880f3214208827bb3205c01a60&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.313/dotnet-sdk-9.0.313-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.313/dotnet-sdk-9.0.313-linux-arm64.tar.gz"
    source-checksum = "sha512:0278c86bcc9c9da2a2be0f43dd34a8cde2d4b1f541ad101c30db44d44536388fa641c57a07a7ac829b7d403112760b172dc608880f3214208827bb3205c01a60"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.313/dotnet-sdk-9.0.313-linux-arm64.tar.gz"
    version = "9.0.313"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:fdc36a27285b6f39b625814454f4dd3e76f2259c1279d0317d7fa297514bba607de323290d42caf67f62b9081ab26b6edb079e00f2b8c709c5826d3349a451d9"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.203:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@10.0.203?checksum=fdc36a27285b6f39b625814454f4dd3e76f2259c1279d0317d7fa297514bba607de323290d42caf67f62b9081ab26b6edb079e00f2b8c709c5826d3349a451d9&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.203/dotnet-sdk-10.0.203-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.203/dotnet-sdk-10.0.203-linux-x64.tar.gz"
    source-checksum = "sha512:fdc36a27285b6f39b625814454f4dd3e76f2259c1279d0317d7fa297514bba607de323290d42caf67f62b9081ab26b6edb079e00f2b8c709c5826d3349a451d9"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.203/dotnet-sdk-10.0.203-linux-x64.tar.gz"
    version = "10.0.203"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:7fbc8e8b20b6d6cb40269544ea4b5e919dd7fc7b066b429f32e7fa9087224f17445b90c7807c46745cc42f299dd7ef65abd023bec03fc341ce07a5bb52a59218"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.203:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-sdk"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core SDK"
    os = "linux"
    purl = "pkg:generic/dotnet-core-sdk@10.0.203?checksum=7fbc8e8b20b6d6cb40269544ea4b5e919dd7fc7b066b429f32e7fa9087224f17445b90c7807c46745cc42f299dd7ef65abd023bec03fc341ce07a5bb52a59218&download_url=https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.203/dotnet-sdk-10.0.203-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.203/dotnet-sdk-10.0.203-linux-arm64.tar.gz"
    source-checksum = "sha512:7fbc8e8b20b6d6cb40269544ea4b5e919dd7fc7b066b429f32e7fa9087224f17445b90c7807c46745cc42f299dd7ef65abd023bec03fc341ce07a5bb52a59218"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/Sdk/10.0.203/dotnet-sdk-10.0.203-linux-arm64.tar.gz"
    version = "10.0.203"

  [[metadata.dependency-constraints]]
    constraint = "8.0.*"
    id = "dotnet-sdk"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "9.0.*"
    id = "dotnet-sdk"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "10.0.*"
    id = "dotnet-sdk"
    patches = 1

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
