name: Update SDK Compatibility Table
"on":
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
  repository_dispatch:
    types:
    - compatibility-table-update
env:
  VERSION: ${{ github.event.client_payload.data.version }}

jobs:
  update:
    name: Update Table
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

    - name: Checkout Branch
      uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
      with:
        branch: automation/dependencies/update

    - name: Set Env Vars
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        fi

    - name: Update the table
      id: update
      uses: paketo-buildpacks/github-config/actions/compatibility@main
      with:
        buildpack_file: "/github/workspace/buildpack.toml"
        sdk_version: ${{ env.VERSION }}
        output_dir: "/github/workspace/buildpack.toml"

    - name: Commit
      id: commit
      uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
      with:
        message: "Updating buildpack.toml compatibility table for SDK v${{ env.VERSION }}"
        pathspec: "."
        keyid: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY_ID }}
        key: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY }}

    - name: Push Branch
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
      with:
        branch: automation/dependencies/update

    - name: Open Pull Request
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/open@main
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        title: "Updating buildpack.toml SDK compatibility table"
        branch: automation/dependencies/update
